version: '3.8'

services:
  cognee:
    image: cognics/cognee:latest
    container_name: networkmind-cognee
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - VECTOR_DB_PROVIDER=qdrant
      - VECTOR_DB_URL=${QDRANT_URL}
      - VECTOR_DB_KEY=${QDRANT_API_KEY}
    volumes:
      - cognee_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  cognee_data:
    driver: local
